### ISSUE TITLE
java.lang.ClassCastException: on decrement/increment

### ISSUE THREAD

**Issue by eddurov** [killme2008/xmemcached#106]
Sometimes incr or decr command returns FALSE in memcache. So xmemcached should expect such behavior, but not cast to Long everytime like this:
`
private long sendIncrOrDecrCommand()
...
return (Long) command.getResult();
...
`
throwing
`
java.lang.Boolean cannot be cast to java.lang.Long
`

**Comment by killme2008** [comment]
What's your memcached version?
