### ISSUE TITLE
Is `incr()` supposed to update expiry time?

### ISSUE THREAD

**Issue by stv8** [killme2008/xmemcached#111]
I've noticed that calling `incr()` with an an expiry such as

` memcachedClient.incr("derp", 1, 1, 5000, 30)`

will set an initial expiry, but subsequent calls to `incr()` with an expiry will not update the expiry and the key expires according to the initial expiry. I followed the execution flow in my debugger and found that the expiry is being sent every time, but maybe I am misunderstanding if memcached even supports updating an expiry. 

With that said, is not updating expiry with subsequent calls intended behavior or a bug?

Thanks!

References:
http://fnil.net/docs/xmemcached/net/rubyeye/xmemcached/MemcachedClient.html#incr(java.lang.String,%20long,%20long,%20long,%20int)
```java
long incr(String key,
        long delta,
        long initValue,
        long timeout,
        int exp)
          throws TimeoutException,
                 InterruptedException,
                 MemcachedException
```

**Comment by killme2008** [comment]
Memcached doesn't support updating expiry with subsequent calls. You can use `touch(key, expires)` instead.

**Comment by stv8** [comment]
Thanks for the follow up!
