### ISSUE TITLE
NOTICE File

### ISSUE THREAD

**Issue by seshagovindan** [killme2008/xmemcached#117]
Hello,
NOTICE file has the details of changelog information rather than having copyright details. I checked the latest version too, same thing. Could you please correct the same and confirm us back. Our legal team is not approving to use this tech for the above said problem.

According to the Apache License 2.0 section 4(d) -- anyone distributing his code in a derivative work must include along with the license

Thanks,
Sesha

**Comment by killme2008** [comment]
Hi, you can remove the NOTICE file in your distribution, but have to keep the License file.
