### ISSUE TITLE
Cannot cache data larer than 1MB

### ISSUE THREAD

**Issue by SieurMonkey** [killme2008/xmemcached#127]
There is a fixed limit for the maximum data size in the CacheData.class from transcoders : 

![image](https://user-images.githubusercontent.com/72027557/98097786-c6d4f800-1e8d-11eb-8dce-c7f4776046a9.png)

However, it's possible to increase the limit size authorized by memcache by passing a "-I" option or by overriding a property (max_item_size) since 1.4.2 version.

I found it possible to edit the max size when using the SerializingTrancoder by setting the transcoder this way : 

![image](https://user-images.githubusercontent.com/72027557/98127238-bf761480-1eb6-11eb-9cd5-26ac0cc10c86.png)

However, I didn't find a way to do so with a StringTranscoder.

**Comment by killme2008** [comment]
2.4.7 发布，增加了 `xmemcached.cached.data.size.max` 系统属性，可以通过 JVM 参数 `-Dxmemcached.cached.data.size.max=xxx` 设置默认最大值。

**Comment by killme2008** [comment]
Released 2.4.7, and it added  a system property `xmemcached.cached.data.size.max` to control the default max size value, you can configure it by adding jvm argument `-Dxmemcached.cached.data.size.max=xxxx`.
