### ISSUE TITLE
Deleting a non-existent key returns false.

### ISSUE THREAD

**Issue by sudo-ankitmishra** [killme2008/xmemcached#131]
When a key is to be deleted from Memcached if is not present then the client is supposed to return NOT FOUND, but I get false.

Code Attachment.
echo "delete kit" | nc  0.0.0.0 11214
it returns NOT FOUND

boolean isDeleted = memcachedClient.delete("kit");
        System.out.println(isDeleted);
this prints false.
we want NOT FOUND here as well.
Thanks,

**Comment by killme2008** [comment]
This behavior is expected, deleting a `NOT FOUND` item returns false.
