### ISSUE TITLE
Is this repository is active and maintained 

### ISSUE THREAD

**Issue by MohanMKR** [killme2008/xmemcached#140]
Hello Team,

We are not seeing a recent update or commit on this project. Xmemcached project is still committed to supporting the project by testing with current browsers or Java versions, and accepting contributions and/or fixing issues as they are reported.

Thank you in advance.

Thanks,

**Comment by jxbadam** [comment]
@killme2008 This is a great question, but may have gone somewhat under the radar. A very quick response would be much appreciated, thank you again for all of this work!

**Comment by killme2008** [comment]
Of, course. The project is still maintained by myself. The memcached project is stable and not updated frequently, so is the xmemcached.

**Comment by jxbadam** [comment]
Thank you for the quick response @killme2008! I expected that it was maintained but at a cadence related to memcache updates, which I believe to be rare.

I did notice some CVE's mentioned in maven central related to dependencies for this project and wondered if those dependencies would be updated at some point ... and I suppose that's also something that could be another issue.

@MohanMKR I believe the above comment solves this issue 👍

**Comment by MohanMKR** [comment]
Thank you for the response and yes it solved this issue. Is there any plans for addressing the CVEs reported on https://mvnrepository.com/artifact/com.googlecode.xmemcached/xmemcached/2.4.7. ?

Most of them related to log4j.

**Comment by killme2008** [comment]
@MartinX3 Sorry, I was busy last weekend, it will be done today.

**Comment by killme2008** [comment]
Already shipped https://github.com/killme2008/xmemcached/releases/tag/xmemcached-2.4.8
