### ISSUE TITLE
Got Incr/Decr on non-numeric value exception

### ISSUE THREAD

**Issue by penggle** [killme2008/xmemcached#24]
I'm using SerializingTranscoder，when set primitiveAsString = false by default it's got exception : Incr/Decr on non-numeric value. For example : memcachedClient.set("inventory", 0, 100); the real value to be set is 'd' (ascll('d') = 100);
when set primitiveAsString = true，the correct value to be store in memcached and can be incr or decr。

**Comment by killme2008** [comment]
It's an expected behavior.
