### ISSUE TITLE
how to make a set of  memcached servers have the same consistent hash?

### ISSUE THREAD

**Issue by ufo5260987423** [killme2008/xmemcached#29]
for example , i have a set of servers includes many tomcat servers and memcached servers.now,i want to tell these tomcat servers memcached servers' addresses,and i want to use consistent hash to organize these servers using xmemcached.

the question is how the same memcached server will have the same hash at different tomcat servers?

**Comment by killme2008** [comment]
If your server list string that is provided to xmemcached client is consistent in these tomcat servers, then xmemcached KetamaMemcachedSessionLocator will make sure that the same key will hit the same memcached server by hashing.
