### ISSUE TITLE
java 和php共用memcache，hash算法一直不一致

### ISSUE THREAD

**Issue by XYangX** [killme2008/xmemcached#33]
PHP采用如下方式：

$mem->setOption(Memcached::OPT_DISTRIBUTION,Memcached::DISTRIBUTION_CONSISTENT); 
$mem->setOption(Memcached::OPT_LIBKETAMA_COMPATIBLE,true); 

java：
builder.setSessionLocator(new KetamaMemcachedSessionLocator());

php使用memcached扩展，开始使用默认设置，不一致，后来改用KETAMA，还是不行

**Comment by killme2008** [comment]
应该是要使用 LibmemcachedMemcachedSessionLocator，并且使用 ONE_AT_A_TIME HashAlgorithm.
