### ISSUE TITLE
Make shutdown hook configurable

### ISSUE THREAD

**Issue by sgmiller** [killme2008/xmemcached#44]
In our server, we register a shutdown hook to cleanly shut the server down.  We have some high priority tasks that rely on getting a few last things written to memcache.  However, with XMemcached, that fails, because its own shutdown hook executes first, killing the connection.

Could we make whether XMemcached uses a shutdown hook configurable (default on)?  In our server, we'd turn it off and use our own hook to call .shutdown() on the client.

**Comment by killme2008** [comment]
Adds a new system env `-Dxmemcached.shutdown.hook.enable=false` to disable shutdown hook.
