### ISSUE TITLE
Disable log4j logging? 

### ISSUE THREAD

**Issue by stodge** [killme2008/xmemcached#46]
This might be a silly question but how do I stop xmemcached from logging output when log4j is configured for DEBUG:

log4j.rootLogger = DEBUG, CONSOLE, LOGFILE

I don't want to see xmemcached's DEBUG logging when I'm debugging my application.

Thanks

**Comment by killme2008** [comment]
You can disable logger by setting log4j properties:

```
log4j.logger.net.rubyeye.xmemcached=false
log4j.logger.com.google.code.yanf4j=false
```
