### ISSUE TITLE
DNS changes requires reinstantiating xmemcached client

### ISSUE THREAD

**Issue by flozano** [killme2008/xmemcached#49]
If a memcached server is restarted and gets a different IP address when recovering, the xmemcached client will never notice of that (as the name is resolved by the builder constructor):
```java
	public XMemcachedClientBuilder(String addressList) {
		this(AddrUtil.getAddresses(addressList));
	}
```

This is a very serious limitation in many dynamic envs (eg: AWS).

**Comment by killme2008** [comment]
Hmm.. It's a problem in such environment.
But memcached is so high reliable, restart is not a common operation.

I will try to find some way to solve this problem, but it's not in high priority,Thanks.

**Comment by flozano** [comment]
Restart of cache nodes is becoming very common in Amazon AWS, and Amazon is a very popular platform... I can see this is not an interesting problem to solve, but I am not sure that assessment about the priority is correct.

**Comment by killme2008** [comment]
Hi,  may i ask why do you often restart memcached instances?

We are using memached in AWS too, but the instances keep running almost 2 years without any operations.

If you want to clear all items in memcached, i think `flush_all` command is a better choice.

**Comment by flozano** [comment]
Hi. Maybe I didn't explain correctly. Memcached instances are restarted not by me, but by Amazon AWS itself.

The reasons when Amazon does it are:
 - underlying hardware is degraded or Amazon wants to replace it.
 - security fixes need to be applied (during maintenance window).

**Comment by killme2008** [comment]
Hi. Thanks, i see. Because we are not using AWS memcached instances but starting memcached  processes by ourself, so we don't have this problem right now.

I will try to figure out a way to solve the problem.

**Comment by flozano** [comment]
Thanks a lot for reconsidering!

**Comment by killme2008** [comment]
@flozano 
Hi, i released 2.1.0 yesterday, you can try it when you are free.

**Comment by flozano** [comment]
Just FYI, we keep having this problem.

**Comment by killme2008** [comment]
Have you upgrade xmc to 2.1.0 or latest version?

**Comment by flozano** [comment]
We're using 2.4.0

Francisco A. Lozano

2017-12-21 12:21 GMT+01:00 dennis zhuang <notifications@github.com>:

**Comment by flozano** [comment]
Reported as https://github.com/killme2008/xmemcached/issues/68
