### ISSUE TITLE
need a builder for AWSElasticCacheClient?

### ISSUE THREAD

**Issue by dkador** [killme2008/xmemcached#55]
hello!

thank you for providing support for node autodiscovery in AWS elasticache. i just tested it out and it looks like it's working so far. if our testing continues to go well, it means we won't have to run twemproxy, which is nice!

in my testing i ran into what might be a configuration/building issue. but i'm new to xmemcached, so perhaps i'm not using it right. basically, i want to be able to set configuration values such as `setConnectionPoolSize`. in our existing code in master, we use the builder pattern given to us via `XMemcachedClientBuilder`. but `AWSElasticCacheClient` doesn't have an associated builder.

so i instantiated it manually and tried to call `setConnectionPoolSize`, but that gives me an `IllegalStateError` as the constructor for `AWSElasticCacheClient` starts the connection.

i also want to set the session idle timeout: `builder.getConfiguration().setSessionIdleTimeout(15000);`

do you have any suggestions for how i can make this work? or do we need a new version that either gives us a builder for `AWSElasticCacheClient` or, perhaps, allows us to not start the `AWSElasticCacheClient` at instantiation time but instead manually?

thanks again!

**Comment by killme2008** [comment]
hi, it's a defect here,  it should provide a builder for AWSElasticCacheClient, thanks for your proposal, i will add it ASAP.

**Comment by dkador** [comment]
thanks for the prompt reply! very much appreciated.

**Comment by killme2008** [comment]
Released 2.3.1, but it may take some time to be synchronized into central repository.

You can download the jar from 

https://github.com/killme2008/xmemcached/releases/tag/xmemcached-2.3.1

**Comment by dkador** [comment]
thank you for the quick turnaround!
