### ISSUE TITLE
Shutdownhook in AbstractController can not be disabled

### ISSUE THREAD

**Issue by mseidel** [killme2008/xmemcached#57]
So, you can disable the shutdownhook in XMemcachedClient, but there is still the one in AbstractController which is not configurable and will always fire, closing the underlying sessions of the client and causing Exceptions if you try to use it during shutdown. I think it should use the same "xmemcached.shutdown.hook.enable" property as the client.

**Comment by killme2008** [comment]
Thanks for your report, AbstractController should respect  `xmemcached.shutdown.hook.enable`,  i will fix it ASAP.
