### ISSUE TITLE
java.util.concurrent.TimeoutException even though memcached server almost unloaded

### ISSUE THREAD

**Issue by adrianbader** [killme2008/xmemcached#66]
I observe sometimes such exceptions:

	07:58:26,346 ERROR [stderr] (default task-35) java.util.concurrent.TimeoutException: Timed out(5000 milliseconds) waiting for operation while connected to xxx:11211
	07:58:26,347 ERROR [stderr] (default task-35) 	at net.rubyeye.xmemcached.XMemcachedClient.latchWait(XMemcachedClient.java:2572)
	07:58:26,347 ERROR [stderr] (default task-35) 	at net.rubyeye.xmemcached.XMemcachedClient.fetch0(XMemcachedClient.java:644)
	07:58:26,347 ERROR [stderr] (default task-35) 	at net.rubyeye.xmemcached.XMemcachedClient.get0(XMemcachedClient.java:1085)
	07:58:26,347 ERROR [stderr] (default task-35) 	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1043)
	07:58:26,347 ERROR [stderr] (default task-35) 	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1054)
	07:58:26,347 ERROR [stderr] (default task-35) 	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1076)

This is strange, because the server has CPU usage below 1%. So I wonder, if I do something wrong with the instatiation of xmemcached client. I use it in a Java EE environment. I created a `@Singleton`, which will build the client on `@PostConstruct`; since xmemcached client should be thread safe, I also annotated `@ConcurrencyManagement(ConcurrencyManagementType.BEAN)` on the singleton. So the whole code looks like:

	@Singleton
	@Startup
	@ConcurrencyManagement(ConcurrencyManagementType.BEAN)
	public class CacheService
	{

		private MemcachedClient memcachedClient;

		@PostConstruct
		private void connect()
		{
			MemcachedClientBuilder builder = new XMemcachedClientBuilder(AddrUtil.getAddresses(host));
			builder.setCommandFactory(new BinaryCommandFactory());
			memcachedClient = builder.build();
		}

		public <T> T cacheGet(String key)
		{
			result = return (T) memcachedClient.get(key);
		}
		
		...
	}

Then I inject this singleton to my service classes (`@Stateless` beans) where I simply call `cacheService.cacheGet(...)`

Is there something wrong with this?

**Comment by killme2008** [comment]
What's the xmemcached version that u are using? And how much  size of the value you put into memcached?

**Comment by adrianbader** [comment]
I use 2.4.0. The size is some 10KiB.
[I do know this reported [issue]https://github.com/killme2008/xmemcached/issues/30) some time ago - this was on method `set`; I have it always on `get`]

**Comment by killme2008** [comment]
Have you tried text protocol? Did it reproduce in text protocol?

**Comment by adrianbader** [comment]
No, I never tried. I can do it.
What you think about my usage? Is this OK?

**Comment by killme2008** [comment]
I think it's ok here, even though the value is a little large. 

Timeout exception may happen in those situation:

1. Network problem
2. JVM Full GC stops too long.
3. The value is too large, and the app load is high, takes too much time on network transport and value decoding/encoding.
4. A bug in xmemcached.

**Comment by killme2008** [comment]
I recommend u to try  text protocol , and see if it happens again.

**Comment by adrianbader** [comment]
What do you mean with "value is a little large"? Which value?

**Comment by killme2008** [comment]
I meant value size, sorry.

**Comment by adrianbader** [comment]
I am not sure whether I understand you correct: You say that the size of objects I put [and I said I put Objects, which are some 10KiB] is probably a little bit large? Well, some of the objectes are probably even 100-300KiB. Is this too much?

**Comment by killme2008** [comment]
Smaller than 1MiB is ok ,but large value would consume much time on network transport.

Have you tried text protocol ?

**Comment by adrianbader** [comment]
Text protocol does not help.
But I think that I found the problem: My application server had too few RAM/Heap. I increased the available RAM on the cointainer (on OpenShift Online 3) and at least until now, I see no more such excpetions...
Thanks anyway for your help!

**Comment by killme2008** [comment]
Hmm. All right, maybe it ran out of memory.

You can find the JVM problem by JVM tools such as jstats/jmap etc.
