### ISSUE TITLE
NIO Connection Pooling - synchronzation

### ISSUE THREAD

**Issue by adrianbader** [killme2008/xmemcached#67]
In the [Wiki](https://github.com/killme2008/xmemcached/wiki/User-Guide), there is written

> XMemcached is base on java NIO, it has one connection to one Memcached server by default, it is very excellent in most projects. But in some typical high-concurrent enviornment, it will has bottleneck too. So Xmemcached support NIO connection pool, it can create multiple connections to one Memcached server. But you should know, they are not synchronized, so you must make sure the synchronzation of data update. You can enable connection pool with following code:

I do not understand this: _**...But you should know, they are not synchronized, so you must make sure the synchronzation of data update...**_
In which situation is a synchronisation needed and why?
Thank you for your help!

**Comment by killme2008** [comment]
The doc does not make sense here, i will remove it.

The real meaning here is that `if you put an item into memcached in thread A with connection A, and you want to get the item in thread B with connection B concurrently, these two operations are not synchronized. If you want B operation  fetching the item successfully, you should make sure that B operation happens after A operation.`

**Comment by adrianbader** [comment]
Thank you for the explanation! I fully agree.
