### ISSUE TITLE
HealSession causes Too many open files

### ISSUE THREAD

**Issue by matejuh** [killme2008/xmemcached#83]
Using HealSession with [SessionMonitor](https://github.com/killme2008/xmemcached/blob/master/src/main/java/net/rubyeye/xmemcached/impl/MemcachedConnector.java#L100).
When instance hostname is unresolvable [connect](https://github.com/killme2008/xmemcached/blob/master/src/main/java/net/rubyeye/xmemcached/impl/MemcachedConnector.java#L462) throws UnresolvedAddressException, but socket is already [opened](https://github.com/killme2008/xmemcached/blob/master/src/main/java/net/rubyeye/xmemcached/impl/MemcachedConnector.java#L459) and not closed. That quickly resolves in Too many open files exception because exception is thrown instead of failing the future, so exponential retry is not used but immediate one. [Number of retries is not updated](https://github.com/killme2008/xmemcached/blob/master/src/main/java/net/rubyeye/xmemcached/impl/MemcachedConnector.java#L118) because exception is thrown, so handled [there](https://github.com/killme2008/xmemcached/blob/master/src/main/java/net/rubyeye/xmemcached/impl/MemcachedConnector.java#L145).

Proposed change (without tests and proper formatting): https://github.com/killme2008/xmemcached/compare/master...matejuh:heal_fix?diff=split&expand=1&name=heal_fix

**Comment by killme2008** [comment]
Thanks for your report, yep, it should close the channel event it's not an IOException here, can you make PR for this? thanks

**Comment by matejuh** [comment]
https://github.com/killme2008/xmemcached/pull/84

**Comment by matejuh** [comment]
Do you plan to release it?

Is there any specific reason why HealThread is not per backend instance (key in sessionMap), but per each connection instance (value in sessionMap)?

**Comment by killme2008** [comment]
```
Do you plan to release it?
```
I will release it tonight.

```
Is there any specific reason why HealThread is not per backend instance (key in sessionMap), but per each connection instance (value in sessionMap)?
```
Because client may use connection pool(session pool).

**Comment by killme2008** [comment]
2.4.4 released.

https://github.com/killme2008/xmemcached/releases/tag/xmemcached-2.4.4

But it may take sometime to be synced into central repository.
