### ISSUE TITLE
java.util.concurrent.TimeoutException: Timed out(1000 milliseconds) waiting for operation while connected to

### ISSUE THREAD

**Issue by leiguorui** [killme2008/xmemcached#86]
您好, 线上总是报连接超时问题,   请问如何排除原因??

目前client的ConnectionPoolSize是30,   memcache服务端的连接数是34819

多谢

**Comment by leiguorui** [comment]
可以排除网络和gc的问题,

因为两台应用服务的日志同时报TimeoutException, 可以排除是某台因为网络和gc的问题

memcache服务的当前连接是34819,  client的ConnectionPoolSize是30,  会不会跟这个有关系??

**Comment by killme2008** [comment]
如果是两台机器同时都报，应该是你的 memcached server 达到瓶颈了，建议扩展资源解决。这个 issue 我关闭了。
