### ISSUE TITLE
Failed connecting to new memcached cluster

### ISSUE THREAD

**Issue by bhaskar20001** [killme2008/xmemcached#97]
Our server nodes will use this memcached client library to connect to with memcached cluster. All these nodes are on AWS cloud.

we have a configuration for our server to connect with memcacheds 
 memcache1.server.mycompany.com:11211,memcache2.server.mycompany.com:11211

Whenever we bring new memcached cluster with same hostnames but with different IPs, memcahced clients are failing to connect with new memcached cluster. And they are still trying to reconnect on old IPs.

Can you help me resolving this problem?
 
Thanks.

**Comment by killme2008** [comment]
What's the xmemcached version are u using?

I think this issue has been solved in #49
